# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/xenoth/.clion-2016.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/xenoth/.clion-2016.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xenoth/ClionProjects/Rampart

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xenoth/ClionProjects/Rampart

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/home/xenoth/.clion-2016.3/bin/cmake/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/home/xenoth/.clion-2016.3/bin/cmake/bin/cpack --config ./CPackSourceConfig.cmake /home/xenoth/ClionProjects/Rampart/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/xenoth/.clion-2016.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/xenoth/.clion-2016.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/xenoth/.clion-2016.3/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/xenoth/.clion-2016.3/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/xenoth/.clion-2016.3/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/xenoth/.clion-2016.3/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xenoth/ClionProjects/Rampart/CMakeFiles /home/xenoth/ClionProjects/Rampart/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xenoth/ClionProjects/Rampart/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rampart

# Build rule for target.
rampart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rampart
.PHONY : rampart

# fast build rule for target.
rampart/fast:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/build
.PHONY : rampart/fast

src/AbstractDynamicEntity.o: src/AbstractDynamicEntity.cpp.o

.PHONY : src/AbstractDynamicEntity.o

# target to build an object file
src/AbstractDynamicEntity.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/AbstractDynamicEntity.cpp.o
.PHONY : src/AbstractDynamicEntity.cpp.o

src/AbstractDynamicEntity.i: src/AbstractDynamicEntity.cpp.i

.PHONY : src/AbstractDynamicEntity.i

# target to preprocess a source file
src/AbstractDynamicEntity.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/AbstractDynamicEntity.cpp.i
.PHONY : src/AbstractDynamicEntity.cpp.i

src/AbstractDynamicEntity.s: src/AbstractDynamicEntity.cpp.s

.PHONY : src/AbstractDynamicEntity.s

# target to generate assembly for a file
src/AbstractDynamicEntity.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/AbstractDynamicEntity.cpp.s
.PHONY : src/AbstractDynamicEntity.cpp.s

src/AbstractEntity.o: src/AbstractEntity.cpp.o

.PHONY : src/AbstractEntity.o

# target to build an object file
src/AbstractEntity.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/AbstractEntity.cpp.o
.PHONY : src/AbstractEntity.cpp.o

src/AbstractEntity.i: src/AbstractEntity.cpp.i

.PHONY : src/AbstractEntity.i

# target to preprocess a source file
src/AbstractEntity.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/AbstractEntity.cpp.i
.PHONY : src/AbstractEntity.cpp.i

src/AbstractEntity.s: src/AbstractEntity.cpp.s

.PHONY : src/AbstractEntity.s

# target to generate assembly for a file
src/AbstractEntity.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/AbstractEntity.cpp.s
.PHONY : src/AbstractEntity.cpp.s

src/AbstractStaticEntity.o: src/AbstractStaticEntity.cpp.o

.PHONY : src/AbstractStaticEntity.o

# target to build an object file
src/AbstractStaticEntity.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/AbstractStaticEntity.cpp.o
.PHONY : src/AbstractStaticEntity.cpp.o

src/AbstractStaticEntity.i: src/AbstractStaticEntity.cpp.i

.PHONY : src/AbstractStaticEntity.i

# target to preprocess a source file
src/AbstractStaticEntity.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/AbstractStaticEntity.cpp.i
.PHONY : src/AbstractStaticEntity.cpp.i

src/AbstractStaticEntity.s: src/AbstractStaticEntity.cpp.s

.PHONY : src/AbstractStaticEntity.s

# target to generate assembly for a file
src/AbstractStaticEntity.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/AbstractStaticEntity.cpp.s
.PHONY : src/AbstractStaticEntity.cpp.s

src/Audio.o: src/Audio.cpp.o

.PHONY : src/Audio.o

# target to build an object file
src/Audio.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Audio.cpp.o
.PHONY : src/Audio.cpp.o

src/Audio.i: src/Audio.cpp.i

.PHONY : src/Audio.i

# target to preprocess a source file
src/Audio.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Audio.cpp.i
.PHONY : src/Audio.cpp.i

src/Audio.s: src/Audio.cpp.s

.PHONY : src/Audio.s

# target to generate assembly for a file
src/Audio.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Audio.cpp.s
.PHONY : src/Audio.cpp.s

src/Bullet.o: src/Bullet.cpp.o

.PHONY : src/Bullet.o

# target to build an object file
src/Bullet.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Bullet.cpp.o
.PHONY : src/Bullet.cpp.o

src/Bullet.i: src/Bullet.cpp.i

.PHONY : src/Bullet.i

# target to preprocess a source file
src/Bullet.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Bullet.cpp.i
.PHONY : src/Bullet.cpp.i

src/Bullet.s: src/Bullet.cpp.s

.PHONY : src/Bullet.s

# target to generate assembly for a file
src/Bullet.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Bullet.cpp.s
.PHONY : src/Bullet.cpp.s

src/BulletsManager.o: src/BulletsManager.cpp.o

.PHONY : src/BulletsManager.o

# target to build an object file
src/BulletsManager.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/BulletsManager.cpp.o
.PHONY : src/BulletsManager.cpp.o

src/BulletsManager.i: src/BulletsManager.cpp.i

.PHONY : src/BulletsManager.i

# target to preprocess a source file
src/BulletsManager.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/BulletsManager.cpp.i
.PHONY : src/BulletsManager.cpp.i

src/BulletsManager.s: src/BulletsManager.cpp.s

.PHONY : src/BulletsManager.s

# target to generate assembly for a file
src/BulletsManager.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/BulletsManager.cpp.s
.PHONY : src/BulletsManager.cpp.s

src/Engine.o: src/Engine.cpp.o

.PHONY : src/Engine.o

# target to build an object file
src/Engine.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Engine.cpp.o
.PHONY : src/Engine.cpp.o

src/Engine.i: src/Engine.cpp.i

.PHONY : src/Engine.i

# target to preprocess a source file
src/Engine.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Engine.cpp.i
.PHONY : src/Engine.cpp.i

src/Engine.s: src/Engine.cpp.s

.PHONY : src/Engine.s

# target to generate assembly for a file
src/Engine.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Engine.cpp.s
.PHONY : src/Engine.cpp.s

src/Explosable.o: src/Explosable.cpp.o

.PHONY : src/Explosable.o

# target to build an object file
src/Explosable.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Explosable.cpp.o
.PHONY : src/Explosable.cpp.o

src/Explosable.i: src/Explosable.cpp.i

.PHONY : src/Explosable.i

# target to preprocess a source file
src/Explosable.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Explosable.cpp.i
.PHONY : src/Explosable.cpp.i

src/Explosable.s: src/Explosable.cpp.s

.PHONY : src/Explosable.s

# target to generate assembly for a file
src/Explosable.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Explosable.cpp.s
.PHONY : src/Explosable.cpp.s

src/Gun.o: src/Gun.cpp.o

.PHONY : src/Gun.o

# target to build an object file
src/Gun.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Gun.cpp.o
.PHONY : src/Gun.cpp.o

src/Gun.i: src/Gun.cpp.i

.PHONY : src/Gun.i

# target to preprocess a source file
src/Gun.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Gun.cpp.i
.PHONY : src/Gun.cpp.i

src/Gun.s: src/Gun.cpp.s

.PHONY : src/Gun.s

# target to generate assembly for a file
src/Gun.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Gun.cpp.s
.PHONY : src/Gun.cpp.s

src/GunsManager.o: src/GunsManager.cpp.o

.PHONY : src/GunsManager.o

# target to build an object file
src/GunsManager.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/GunsManager.cpp.o
.PHONY : src/GunsManager.cpp.o

src/GunsManager.i: src/GunsManager.cpp.i

.PHONY : src/GunsManager.i

# target to preprocess a source file
src/GunsManager.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/GunsManager.cpp.i
.PHONY : src/GunsManager.cpp.i

src/GunsManager.s: src/GunsManager.cpp.s

.PHONY : src/GunsManager.s

# target to generate assembly for a file
src/GunsManager.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/GunsManager.cpp.s
.PHONY : src/GunsManager.cpp.s

src/MapManager.o: src/MapManager.cpp.o

.PHONY : src/MapManager.o

# target to build an object file
src/MapManager.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/MapManager.cpp.o
.PHONY : src/MapManager.cpp.o

src/MapManager.i: src/MapManager.cpp.i

.PHONY : src/MapManager.i

# target to preprocess a source file
src/MapManager.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/MapManager.cpp.i
.PHONY : src/MapManager.cpp.i

src/MapManager.s: src/MapManager.cpp.s

.PHONY : src/MapManager.s

# target to generate assembly for a file
src/MapManager.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/MapManager.cpp.s
.PHONY : src/MapManager.cpp.s

src/Ship.o: src/Ship.cpp.o

.PHONY : src/Ship.o

# target to build an object file
src/Ship.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Ship.cpp.o
.PHONY : src/Ship.cpp.o

src/Ship.i: src/Ship.cpp.i

.PHONY : src/Ship.i

# target to preprocess a source file
src/Ship.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Ship.cpp.i
.PHONY : src/Ship.cpp.i

src/Ship.s: src/Ship.cpp.s

.PHONY : src/Ship.s

# target to generate assembly for a file
src/Ship.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Ship.cpp.s
.PHONY : src/Ship.cpp.s

src/ShipsManager.o: src/ShipsManager.cpp.o

.PHONY : src/ShipsManager.o

# target to build an object file
src/ShipsManager.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/ShipsManager.cpp.o
.PHONY : src/ShipsManager.cpp.o

src/ShipsManager.i: src/ShipsManager.cpp.i

.PHONY : src/ShipsManager.i

# target to preprocess a source file
src/ShipsManager.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/ShipsManager.cpp.i
.PHONY : src/ShipsManager.cpp.i

src/ShipsManager.s: src/ShipsManager.cpp.s

.PHONY : src/ShipsManager.s

# target to generate assembly for a file
src/ShipsManager.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/ShipsManager.cpp.s
.PHONY : src/ShipsManager.cpp.s

src/Shootable.o: src/Shootable.cpp.o

.PHONY : src/Shootable.o

# target to build an object file
src/Shootable.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Shootable.cpp.o
.PHONY : src/Shootable.cpp.o

src/Shootable.i: src/Shootable.cpp.i

.PHONY : src/Shootable.i

# target to preprocess a source file
src/Shootable.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Shootable.cpp.i
.PHONY : src/Shootable.cpp.i

src/Shootable.s: src/Shootable.cpp.s

.PHONY : src/Shootable.s

# target to generate assembly for a file
src/Shootable.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Shootable.cpp.s
.PHONY : src/Shootable.cpp.s

src/Territory.o: src/Territory.cpp.o

.PHONY : src/Territory.o

# target to build an object file
src/Territory.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Territory.cpp.o
.PHONY : src/Territory.cpp.o

src/Territory.i: src/Territory.cpp.i

.PHONY : src/Territory.i

# target to preprocess a source file
src/Territory.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Territory.cpp.i
.PHONY : src/Territory.cpp.i

src/Territory.s: src/Territory.cpp.s

.PHONY : src/Territory.s

# target to generate assembly for a file
src/Territory.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/Territory.cpp.s
.PHONY : src/Territory.cpp.s

src/TileMap.o: src/TileMap.cpp.o

.PHONY : src/TileMap.o

# target to build an object file
src/TileMap.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/TileMap.cpp.o
.PHONY : src/TileMap.cpp.o

src/TileMap.i: src/TileMap.cpp.i

.PHONY : src/TileMap.i

# target to preprocess a source file
src/TileMap.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/TileMap.cpp.i
.PHONY : src/TileMap.cpp.i

src/TileMap.s: src/TileMap.cpp.s

.PHONY : src/TileMap.s

# target to generate assembly for a file
src/TileMap.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/TileMap.cpp.s
.PHONY : src/TileMap.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/rampart.dir/build.make CMakeFiles/rampart.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... package"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... rampart"
	@echo "... src/AbstractDynamicEntity.o"
	@echo "... src/AbstractDynamicEntity.i"
	@echo "... src/AbstractDynamicEntity.s"
	@echo "... src/AbstractEntity.o"
	@echo "... src/AbstractEntity.i"
	@echo "... src/AbstractEntity.s"
	@echo "... src/AbstractStaticEntity.o"
	@echo "... src/AbstractStaticEntity.i"
	@echo "... src/AbstractStaticEntity.s"
	@echo "... src/Audio.o"
	@echo "... src/Audio.i"
	@echo "... src/Audio.s"
	@echo "... src/Bullet.o"
	@echo "... src/Bullet.i"
	@echo "... src/Bullet.s"
	@echo "... src/BulletsManager.o"
	@echo "... src/BulletsManager.i"
	@echo "... src/BulletsManager.s"
	@echo "... src/Engine.o"
	@echo "... src/Engine.i"
	@echo "... src/Engine.s"
	@echo "... src/Explosable.o"
	@echo "... src/Explosable.i"
	@echo "... src/Explosable.s"
	@echo "... src/Gun.o"
	@echo "... src/Gun.i"
	@echo "... src/Gun.s"
	@echo "... src/GunsManager.o"
	@echo "... src/GunsManager.i"
	@echo "... src/GunsManager.s"
	@echo "... src/MapManager.o"
	@echo "... src/MapManager.i"
	@echo "... src/MapManager.s"
	@echo "... src/Ship.o"
	@echo "... src/Ship.i"
	@echo "... src/Ship.s"
	@echo "... src/ShipsManager.o"
	@echo "... src/ShipsManager.i"
	@echo "... src/ShipsManager.s"
	@echo "... src/Shootable.o"
	@echo "... src/Shootable.i"
	@echo "... src/Shootable.s"
	@echo "... src/Territory.o"
	@echo "... src/Territory.i"
	@echo "... src/Territory.s"
	@echo "... src/TileMap.o"
	@echo "... src/TileMap.i"
	@echo "... src/TileMap.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

